export type Workout = {
    week: number
    weekDay: string
    exercise: string
    series: number | string
    repetitions: string | number
    rest: string | number | null
    kg: number | null
    technique?: string
    done: boolean
}

export const makeWorkout = (): Workout[] => [
    {
        week: 1,
        weekDay: "Tuesday",
        exercise: "Agachamento Livre",
        series: 2,
        repetitions: "no repeat",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 1,
        weekDay: "Tuesday",
        exercise: "Supino Máquina",
        series: 2,
        repetitions: "no repeat",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 1,
        weekDay: "Tuesday",
        exercise: "Pulley Frente",
        series: 2,
        repetitions: "no repeat",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 1,
        weekDay: "Tuesday",
        exercise: "Desenvolvimento com Dumbbells",
        series: 2,
        repetitions: "no repeat",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 1,
        weekDay: "Tuesday",
        exercise: "Abs Solo",
        series: 2,
        repetitions: "no repeat",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 1,
        weekDay: "Tuesday",
        exercise: "ABS Bike",
        series: 3,
        repetitions: "15/15",
        rest: 45,
        kg: null,
        done: false,
    },
    {
        week: 1,
        weekDay: "Tuesday",
        exercise: "ABS Infra Deitado",
        series: 3,
        repetitions: "15",
        rest: 45,
        kg: null,
        done: false,
    },
    {
        week: 1,
        weekDay: "Wednesday",
        exercise: "Leg Press (Leg Press 45º)",
        series: 2,
        repetitions: "no repeat",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 1,
        weekDay: "Wednesday",
        exercise: "Remada Pronada Aberta",
        series: 2,
        repetitions: "no repeat",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 1,
        weekDay: "Wednesday",
        exercise: "Dumbbell Press Reto",
        series: 2,
        repetitions: "no repeat",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 1,
        weekDay: "Wednesday",
        exercise: "Elevação Lateral",
        series: 2,
        repetitions: "no repeat",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 1,
        weekDay: "Wednesday",
        exercise: "Prancha Ventral",
        series: 2,
        repetitions: "no repeat",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 1,
        weekDay: "Thursday",
        exercise: "Agachamento Hack",
        series: 2,
        repetitions: "no repeat",
        rest: "1min",
        kg: null,
        done: false,
    },
    {
        week: 1,
        weekDay: "Thursday",
        exercise: "Pulley Frente Triângulo",
        series: 2,
        repetitions: "no repeat",
        rest: "1min",
        kg: null,
        done: false,
    },
    {
        week: 1,
        weekDay: "Thursday",
        exercise: "Crucifixo Máquina",
        series: 2,
        repetitions: "no repeat",
        rest: "1min",
        kg: null,
        done: false,
    },
    {
        week: 1,
        weekDay: "Thursday",
        exercise: "Deltoide Posterior Máquina",
        series: 2,
        repetitions: "no repeat",
        rest: "1min",
        kg: null,
        done: false,
    },
    {
        week: 1,
        weekDay: "Thursday",
        exercise: "Abdominal Máquina",
        series: 2,
        repetitions: "no repeat",
        rest: "1min",
        kg: null,
        done: false,
    },
    {
        week: 1,
        weekDay: "Thursday",
        exercise: "Abs Supra Solo com Mão Deslizando",
        series: 3,
        repetitions: "15",
        rest: "1min",
        kg: null,
        done: false,
    },
    {
        week: 1,
        weekDay: "Thursday",
        exercise: "ABS Sit Up",
        series: 3,
        repetitions: "15",
        rest: "1min",
        kg: null,
        done: false,
    },
    {
        week: 2,
        weekDay: "Tuesday",
        exercise: "Agachamento Livre",
        series: 2,
        repetitions: "no repeat",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 2,
        weekDay: "Tuesday",
        exercise: "Supino Reto",
        series: 2,
        repetitions: "no repeat",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 2,
        weekDay: "Tuesday",
        exercise: "Pulley Frente Triângulo",
        series: 2,
        repetitions: "no repeat",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 2,
        weekDay: "Tuesday",
        exercise: "Desenvolvimento com Dumbbells",
        series: 2,
        repetitions: "no repeat",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 2,
        weekDay: "Tuesday",
        exercise: "Abs Supra Solo com Mão Deslizando",
        series: 3,
        repetitions: 20,
        rest: 45,
        kg: null,
        done: false,
    },
    {
        week: 2,
        weekDay: "Tuesday",
        exercise: "ABS Sit Up",
        series: 3,
        repetitions: 20,
        rest: 45,
        kg: null,
        done: false,
    },
    {
        week: 2,
        weekDay: "Tuesday",
        exercise: "ABS Prancha c/ Toque no Ombro",
        series: 3,
        repetitions: "20/20",
        rest: 45,
        kg: null,
        done: false,
    },
    {
        week: 2,
        weekDay: "Wednesday",
        exercise: "Leg Press (Leg Press 45º)",
        series: 2,
        repetitions: "10 a 15",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 2,
        weekDay: "Wednesday",
        exercise: "Remada Baixa Triângulo",
        series: 2,
        repetitions: "10 a 15",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 2,
        weekDay: "Wednesday",
        exercise: "Dumbbell Press Reto",
        series: 2,
        repetitions: "10 a 15",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 2,
        weekDay: "Wednesday",
        exercise: "Elevação Lateral",
        series: 2,
        repetitions: "10 a 15",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 2,
        weekDay: "Wednesday",
        exercise: "esteria",
        series: "15 min",
        repetitions: "1 - passada rapida",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 2,
        weekDay: "Thursday",
        exercise: "Afundo",
        series: 2,
        repetitions: "10 a 15",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 2,
        weekDay: "Thursday",
        exercise: "Remada Máquina Fechada",
        series: 2,
        repetitions: "10 a 15",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 2,
        weekDay: "Thursday",
        exercise: "Crossover",
        series: 2,
        repetitions: "10 a 15",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 2,
        weekDay: "Thursday",
        exercise: "Crucifixo Inverso",
        series: 2,
        repetitions: "10 a 15",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 2,
        weekDay: "Thursday",
        exercise: "Prancha Ventral",
        series: 2,
        repetitions: "10 a 15",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 2,
        weekDay: "Thursday",
        exercise: "Abs Supra Solo com Mão Deslizando",
        series: 3,
        repetitions: "15/15",
        rest: 45,
        kg: null,
        done: false,
    },
    {
        week: 2,
        weekDay: "Thursday",
        exercise: "ABS Remador Alternado",
        series: 3,
        repetitions: "10/10",
        rest: 45,
        kg: null,
        done: false,
    },
    {
        week: 3,
        weekDay: "Tuesday",
        exercise: "Agachamento Búlgaro",
        series: 2,
        repetitions: "10 a 15",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 3,
        weekDay: "Tuesday",
        exercise: "Supino Máquina",
        series: 2,
        repetitions: "10 a 15",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 3,
        weekDay: "Tuesday",
        exercise: "Pulley Frente",
        series: 2,
        repetitions: "10 a 15",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 3,
        weekDay: "Tuesday",
        exercise: "Desenvolvimento com Dumbbells",
        series: 2,
        repetitions: "10 a 15",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 3,
        weekDay: "Tuesday",
        exercise: "Abdominal Máquina",
        series: 2,
        repetitions: "10 a 15",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 3,
        weekDay: "Tuesday",
        exercise: "ABS Rodinha",
        series: 3,
        repetitions: 12,
        rest: 45,
        kg: null,
        done: false,
    },
    {
        week: 3,
        weekDay: "Tuesday",
        exercise: "ABS Supra na Bola Suíça",
        series: 3,
        repetitions: 12,
        rest: 45,
        kg: null,
        technique: "Rest Pause",
        done: false,
    },
    {
        week: 3,
        weekDay: "Wednesday",
        exercise: "Leg Press Unilateral",
        series: 2,
        repetitions: "10 a 15",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 3,
        weekDay: "Wednesday",
        exercise: "Remada Pronada Aberta",
        series: 2,
        repetitions: "10 a 15",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 3,
        weekDay: "Wednesday",
        exercise: "Dumbbell Press Reto",
        series: 2,
        repetitions: "10 a 15",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 3,
        weekDay: "Wednesday",
        exercise: "Elevação Lateral",
        series: 2,
        repetitions: "10 a 15",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 3,
        weekDay: "Wednesday",
        exercise: "Prancha Ventral",
        series: 2,
        repetitions: "10 a 15",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 3,
        weekDay: "Thursday",
        exercise: "Agachamento Livre",
        series: 2,
        repetitions: "10 a 15",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 3,
        weekDay: "Thursday",
        exercise: "Pulley Frente",
        series: 2,
        repetitions: "10 a 15",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 3,
        weekDay: "Thursday",
        exercise: "Crucifixo Máquina",
        series: 2,
        repetitions: "10 a 15",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 3,
        weekDay: "Thursday",
        exercise: "Deltoide Posterior Máquina",
        series: 2,
        repetitions: "10 a 15",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 3,
        weekDay: "Thursday",
        exercise: "ABS Remador",
        series: 3,
        repetitions: 18,
        rest: 45,
        kg: null,
        technique: "Rest Pause",
        done: false,
    },
    {
        week: 3,
        weekDay: "Thursday",
        exercise: "ABS Infra Tesoura",
        series: 3,
        repetitions: 18,
        rest: 45,
        kg: null,
        done: false,
    },
    {
        week: 4,
        weekDay: "Tuesday",
        exercise: "Agachamento Livre",
        series: 2,
        repetitions: "10 a 15",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 4,
        weekDay: "Tuesday",
        exercise: "Leg Press (Leg Press 45º)",
        series: 2,
        repetitions: "10 a 15",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 4,
        weekDay: "Tuesday",
        exercise: "Cadeira Extensora",
        series: 2,
        repetitions: "10 a 15",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 4,
        weekDay: "Tuesday",
        exercise: "Cadeira Adutora",
        series: 2,
        repetitions: "10 a 15",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 4,
        weekDay: "Tuesday",
        exercise: "Panturrilha em Pé",
        series: 3,
        repetitions: "10 a 15",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 4,
        weekDay: "Tuesday",
        exercise: "ABS Rodinha",
        series: 3,
        repetitions: 12,
        rest: 45,
        kg: null,
        technique: "Rest Pause",
        done: false,
    },
    {
        week: 4,
        weekDay: "Tuesday",
        exercise: "ABS Supra na Bola Suíça",
        series: 3,
        repetitions: 12,
        rest: 45,
        kg: null,
        done: false,
    },
    {
        week: 4,
        weekDay: "Tuesday",
        exercise: "ABS Canoa",
        series: 3,
        repetitions: "30''",
        rest: 45,
        kg: null,
        done: false,
    },
    {
        week: 4,
        weekDay: "Wednesday",
        exercise: "Remada Máquina Pronada Aberta",
        series: 2,
        repetitions: "10 a 15",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 4,
        weekDay: "Wednesday",
        exercise: "Pulley Frente Triângulo",
        series: 2,
        repetitions: "10 a 15",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 4,
        weekDay: "Wednesday",
        exercise: "Deltoide Posterior Máquina",
        series: 2,
        repetitions: "10 a 15",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 4,
        weekDay: "Wednesday",
        exercise: "Rosca Simultânea",
        series: 2,
        repetitions: "10 a 15",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 4,
        weekDay: "Wednesday",
        exercise: "Rosca Martelo",
        series: 2,
        repetitions: "10 a 15",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 4,
        weekDay: "Thursday",
        exercise: "Agachamento Livre",
        series: 2,
        repetitions: "10 a 15",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 4,
        weekDay: "Thursday",
        exercise: "Leg Press (Leg Press 45º)",
        series: 2,
        repetitions: "10 a 15",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 4,
        weekDay: "Thursday",
        exercise: "Cadeira Flexora",
        series: 2,
        repetitions: "10 a 15",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 4,
        weekDay: "Thursday",
        exercise: "Stiff",
        series: 2,
        repetitions: "10 a 15",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 4,
        weekDay: "Thursday",
        exercise: "Cadeira Abdutora",
        series: 2,
        repetitions: "10 a 15",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 4,
        weekDay: "Thursday",
        exercise: "ABS Remador",
        series: 3,
        repetitions: 18,
        rest: 45,
        kg: null,
        technique: "Rest Pause",
        done: false,
    },
    {
        week: 4,
        weekDay: "Thursday",
        exercise: "ABS Infra Tesoura",
        series: 3,
        repetitions: 18,
        rest: 45,
        kg: null,
        done: false,
    },
    {
        week: 4,
        weekDay: "Thursday",
        exercise: "ABS Bike",
        series: 3,
        repetitions: 15,
        rest: 45,
        kg: null,
        done: false,
    },
    {
        week: 4,
        weekDay: "Saturday",
        exercise: "Supino Máquina",
        series: 2,
        repetitions: "10 a 15",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 4,
        weekDay: "Saturday",
        exercise: "Dumbbell Press Reto",
        series: 2,
        repetitions: "10 a 15",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 4,
        weekDay: "Saturday",
        exercise: "Elevação Lateral",
        series: 2,
        repetitions: "10 a 15",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 4,
        weekDay: "Saturday",
        exercise: "Tríceps Pulley",
        series: 2,
        repetitions: "10 a 15",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 4,
        weekDay: "Saturday",
        exercise: "Tríceps Pulley Corda",
        series: 2,
        repetitions: "10 a 15",
        rest: null,
        kg: null,
        done: false,
    },
    {
        week: 4,
        weekDay: "Saturday",
        exercise: "Prancha Ventral",
        series: 3,
        repetitions: "10 a 15",
        rest: null,
        kg: null,
        done: false,
    },
]
